import { createFileRoute, Link } from "@tanstack/react-router";
import { Header, Footer, Eyebrow, ContactForm, services, serviceIcons, CONSULT_WHATSAPP, WHATSAPP, PHONE, EMAIL, ArrowUpRight, Phone, Mail, MessageCircle } from "../components/halden-site";

export const Route = createFileRoute("/")({ head: () => ({ meta: [
  { title: "Halden Consulting Group | Kenya & East Africa" },
  { name: "description", content: "Practical consulting for agriculture, NGOs, human rights and community organizations in Kenya and East Africa. Speak with Denis at Halden Consulting Group." },
  { property: "og:title", content: "Halden Consulting Group | Kenya & East Africa" },
  { property: "og:description", content: "Practical consulting for agriculture, NGOs, human rights and community organizations in Kenya and East Africa." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: Index });

function Index() { return <div className="site-grain"><Header/><main>
  <section className="hero"><div className="hero-rings"><i/><i/><i/><b/></div><div className="hero-inner"><div><Eyebrow light>Independent expertise · Kenya &amp; East Africa</Eyebrow><h1>Expert Consulting for <span>Agriculture, NGOs</span> &amp; Human Rights</h1><p>Empowering Sustainable Growth Through Expert Consultation</p><div className="hero-actions"><a href={CONSULT_WHATSAPP}>Book via WhatsApp - KES 3,500 <MessageCircle size={17}/></a><a href={WHATSAPP}><MessageCircle size={17}/> WhatsApp Denis</a></div><div className="hero-note"><i/>Practical guidance. Locally grounded.</div></div><div className="hero-art"><div><p>Good work begins with a clearer path forward.</p><small>CONSULTATION WITH DENIS</small></div><b>HCG</b></div></div><div className="hero-bottom"><span>♧ &nbsp; Agriculture &amp; agribusiness</span><span>♧ &nbsp; NGOs &amp; community organizations</span><span>⚖ &nbsp; Human rights &amp; advocacy</span></div></section>
  <section id="about" className="about"><div><Eyebrow>Who we are</Eyebrow><h2>Rooted in people. Focused on progress.</h2><p>Halden Consulting Group Limited provides considered, practical consulting to people and organizations working to make a difference.</p><a href="#contact">START A CONVERSATION <ArrowUpRight size={15}/></a></div><div className="values-grid"><article><i>◎</i><h3>Our mission</h3><p>To empower sustainable growth through expert consultation, practical insight and purposeful collaboration.</p></article><article><i>⊙</i><h3>Our vision</h3><p>A future where communities and organizations have the clarity and support to build lasting, sustainable progress.</p></article><article><b>OUR CORE VALUES</b><div>{["Integrity","Practicality","Respect","Inclusion","Sustainability"].map(x=><span key={x}>{x}</span>)}</div></article></div></section>
  <section id="services" className="services"><div className="section-inner"><div className="section-heading"><div><Eyebrow>What we do</Eyebrow><h2>Expertise shaped around your work.</h2></div><p>The right support depends on where you are and what you are working toward. Explore our areas of consulting.</p></div><div className="services-grid">{services.map(([name, copy], i) => { const Icon=serviceIcons[i]; return <article key={name}><div>{Icon ? <Icon size={21}/> : null}<span>{String(i+1).padStart(2,"0")}</span></div><h3>{name}</h3><p>{copy}</p><Link to="/book" search={{ package: "starter", service: name } as never}>PAY &amp; BOOK THIS SERVICE <ArrowUpRight size={14}/></Link></article>})}</div><div className="services-cta"><p>Not sure where to start? Tell us what you are working on.</p><Link to="/book">BOOK A CONSULTATION <ArrowUpRight size={15}/></Link></div></div></section>
  <section id="approach" className="approach"><div className="section-inner"><div className="section-heading"><div><Eyebrow>Why Halden</Eyebrow><h2>A thoughtful partner for the work ahead.</h2></div><div><p>Useful advice respects your context, makes room for people and moves toward action.</p><Link to="/book">TALK WITH DENIS <ArrowUpRight size={14}/></Link></div></div><div className="approach-grid">{[["Locally grounded","Advice attentive to the realities of Kenya and the wider East African region."],["Practical by design","Clear steps and useful recommendations, not complexity for its own sake."],["People first","Respectful collaboration with farmers, teams and the communities they serve."],["Purpose-led","Support across agriculture, civil society, human rights and sustainable development."]].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
  <section id="impact" className="impact"><div className="section-inner"><Eyebrow light>Projects / Impact</Eyebrow><div className="impact-grid"><div><h2>Impact is built together, one useful step at a time.</h2><p>We work alongside clients to help move important work forward. Each engagement starts with listening, a clear understanding of the need and a shared sense of what progress could look like.</p></div><blockquote><b>“</b><p>Every project is different. Our role is to bring structure, perspective and practical support to the work in front of you.</p><small>OUR APPROACH TO IMPACT</small></blockquote></div></div></section>
  <section className="next-step"><Eyebrow>A clear next step</Eyebrow><h2>Let’s move your work forward.</h2><div><Link to="/book">BOOK A CONSULTATION <ArrowUpRight size={15}/></Link><a href={WHATSAPP}>WHATSAPP DENIS <MessageCircle size={15}/></a></div></section>
  <section id="contact" className="contact"><div className="contact-grid"><div><Eyebrow>Contact</Eyebrow><h2>Let’s talk about what you’re building.</h2><p>Share a little about your work. Denis will be glad to hear from you.</p><div className="contact-details"><a href={`mailto:${EMAIL}`}><Mail/><span><b>EMAIL</b>{EMAIL}</span></a><a href={`tel:${PHONE}`}><Phone/><span><b>CALL DENIS</b>+254 729 055 293</span></a><div><span>WORKING HOURS</span><b>Monday–Saturday, 8am–6pm</b></div></div></div><ContactForm/></div></section>
  </main><Footer/></div> }
